Dev 3753
letsdeel/money pull request #1
Opened 2020-11-26 13:28 UTC by msantos-sw

Implemented methods that will be used by backend project.

2020-11-30 09:05 UTC, gilad-deel requested changes

2020-11-30 09:05 UTC, gilad-deel commented on index.js
> +    if (!m[0] instanceof Money) throw new Error('invalid argument');
you need to surround this with brackets

2020-11-30 09:05 UTC, gilad-deel commented on index.js
> +    return m.reduce((acc, a) => {
no need to pass `null` nor check it after. Please read about `reduce` syntax

2020-11-30 09:05 UTC, gilad-deel commented on index.js
> +        if (acc === null || Money(a).gt(acc)) { acc = a; }
https://github.com/letsdeel/backend/blob/dev/coding.md#blocks

2020-12-22 14:32 UTC, msantos-sw commented on index.js
> +    if (v === null || v === undefined || v instanceof Money) throw new Error('invalid argument');
fixed

2020-12-22 14:32 UTC, msantos-sw commented on index.js
> +    if (v === null || v === undefined || v instanceof Money) throw new Error('invalid argument');
fixed

2020-12-22 14:32 UTC, msantos-sw commented on index.js
> +    return this.amount.toNumber() === 0;
fixed

2020-12-22 14:32 UTC, msantos-sw commented on index.js
> +    return this.amount.toNumber() >= 0;
fixed

2020-12-22 14:32 UTC, msantos-sw commented on index.js
> +    if (!m[0] instanceof Money) throw new Error('invalid argument');
fixed

2020-12-22 14:33 UTC, msantos-sw commented on index.js
> +    return m.reduce((acc, a) => {
fixed

2020-12-22 14:33 UTC, msantos-sw commented on index.js
> +        if (acc === null || Money(a).gt(acc)) { acc = a; }
fixed

2021-01-21 18:42 UTC, merged